# Generated by Django 4.0.3 on 2022-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=20)),
                ('book_id', models.CharField(max_length=20)),
                ('count', models.CharField(max_length=3)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
